add precision 7
dahlia/wikidata pull request #59
Opened 2024-06-25 13:52 UTC by BaptisteBayche

Following the issue #58 I create this pull request.
I propose this change to fix this error `7: time precision other than 9, 11 or 14 is unsupported wikidata {'type': 'time', 'value': {'time': '+2000-00-00T00:00:00Z', 'timezone': 0, 'before': 0, 'after': 0, 'precision': 7, 'calendarmodel': 'http://www.wikidata.org/entity/Q1985727'}}.`

2024-06-25 13:54 UTC, dahlia reviewed
Could you please add a changelog entry to the *docs/changes.rst* file?

2024-06-25 15:27 UTC, BaptisteBayche commented
Hi,

Thank you for your reply.
I just came to add the entry in the changelog. Is it fine like that?

2024-06-25 15:29 UTC, dahlia approved these changes
Everything looks good to me.  Thanks for your first contribution!

2024-06-25 15:33 UTC, dahlia requested changes
Oh, tests seem fail.  Could you fix the tests?  See also [how to run tests](https://github.com/dahlia/wikidata/blob/main/CONTRIBUTING.rst#how-to-run-tests).

2024-06-26 01:20 UTC, dahlia approved these changes
Thanks!

2024-06-26 01:21 UTC, merged