time precision 10
dahlia/wikidata pull request #60
Opened 2024-07-05 17:07 UTC by DavidDoukhan

Dear maintainer,

Please find a proposal for the management of time values associated to a precision argument of value 10.
This value is used for dates containing only year and month (no day).
See https://www.wikidata.org/wiki/Help:Dates#Precision

I chose to return a tuple (year, month) in this situation, since the python datetime requires a day, and that a single int value is used when the year only is used. This choice allow to distinguish between the different time precisions that could be used.

I also updated the test set.

Let me know if this proposal is consistent with your project.

Kind regards,

2024-07-05 17:10 UTC, DavidDoukhan commented
I also updated the Contributing.rst ro remove the installation of tox-pip-version.
When installing this package, I was not able to run the test suite.
Removing it from installation fixed this problem.

2024-07-06 03:36 UTC, dahlia requested changes
Thanks for your first contribution!

Mypy typechecker seems to fail.  Could you add `Tuple[int, int]` to the union, a return type of `time()` method?

2024-07-06 06:41 UTC, DavidDoukhan commented
Requested changes were addressed. Please let me know if it's ok for you.

2024-07-06 18:31 UTC, DavidDoukhan commented
I don't understand why the  "main / check (pull_request)" failed. Any idea ?
A re-run may be enough ?

2024-07-07 03:13 UTC, dahlia commented
> I don't understand why the "main / check (pull_request)" failed. Any idea ? A re-run may be enough ?

That's an existing problem.  Never mind!  I'm going to merge this anyway.

2024-07-07 03:14 UTC, merged